### ISSUE TITLE
Frete obrigatório

### ISSUE THREAD

**Issue by henriquuepedro** [felipe-ssilva/vtex-urls#2]
Olá, estou tentando integrar com a vtex, mas quando envio um pedido, a vtex não me deixa enviar o meu valor de frete precisa ser o frete deles, sabe dizer se tem como ignorar essa validação?

**Comment by felipe-ssilva** [comment]
Oi @Henriquuepedro como você está fazendo? Consegue dar mais detalhes?

**Comment by henriquuepedro** [comment]
Olá @felipe-ssilva desculpa a demora, estou recebendo a seguinte mensagem: **"O valor do frete foi alterado"** quando faço o envio do pedido para a vtex no seguinte endpoint: **https://gruposoma.vtexcommercestable.com.br/api/checkout/pub/orders**, sabe dizer se é possível informar um valor diferente do que a vtex sugere?

// dados frete
"logisticsInfo": [{
    "itemIndex": 0,
    "selectedSla": "Expressa",
    "price": 3420
}]

// retorno
"messages": [
	{
		"code": null,
		"text": "O valor do frete foi alterado",
		"status": "warning",
		"fields": {}
	}
]
